# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Echo-WM Flash causal audio-video pipeline.

Implements the 4-step DMD causal rollout of Echo-WM Flash on top of the
Echo-WM transformer port: an image-sink commit, an audio-prefix denoise, then
3-latent-frame audio-video chunks, each denoised with four probe forwards and
one clean commit forward, with bounded sink+FIFO caches carrying history.

v1 scope: the pipeline consumes a pre-encoded first-frame latent and either
precomputed text embeddings (the precision path: fixtures generated by the
reference implementation) or an in-process Gemma encoder, and emits latents
plus chunk metadata. Pixel VAE decode stays outside the engine (the reference
decoder is used by the verification harness); serving it in-engine is a
follow-up together with the AR paged-KV branch, which the current
single-geometry paged spec cannot express for Echo-WM's mixed audio/video
head sizes.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from types import SimpleNamespace
from typing import Any, ClassVar

import torch
from safetensors import safe_open
from torch import nn
from vllm.logger import init_logger

from vllm_omni.diffusion.data import DiffusionOutput, OmniDiffusionConfig
from vllm_omni.diffusion.models.echo_wm.causal_cache import (
    DEFAULT_CAUSAL_TIMESTEPS,
    EchoWMCacheConfig,
    build_audio_positions,
    build_video_positions,
    causal_audio_blocks,
    causal_audio_frames,
    causal_video_blocks,
    compute_cross_slices,
    make_cross_rope_template,
    make_split_rope,
    resolve_causal_sigmas,
)
from vllm_omni.diffusion.models.echo_wm.text_stack import EchoWMTextStack
from vllm_omni.diffusion.models.echo_wm.transformer import EchoWMTransformer3DModel, EchoWMUCPEConfig
from vllm_omni.diffusion.models.interface import SupportsComponentDiscovery, SupportsStepExecution
from vllm_omni.diffusion.models.progress_bar import ProgressBarMixin
from vllm_omni.diffusion.worker.request_batch import DiffusionRequestBatch
from vllm_omni.diffusion.worker.utils import StepRequestState

logger = init_logger(__name__)

_DEFAULT_RESOLUTION = (1280, 704)
_DEFAULT_FPS = 24.0
_ECHOWM_DMD_STEPS = 4


def _read_checkpoint_config(checkpoint_path: str) -> dict[str, Any]:
    with safe_open(checkpoint_path, framework="pt") as handle:
        metadata = handle.metadata() or {}
    config = metadata.get("config")
    if config is None:
        raise ValueError(f"{checkpoint_path} does not embed an Echo-WM model config")
    return json.loads(config)


@dataclass
class _EchoWMRequestInputs:
    height: int
    width: int
    num_frames: int
    fps: float
    seed: int
    timesteps: tuple[int, ...]
    cache_config: EchoWMCacheConfig
    image_latent_tokens: torch.Tensor  # (1, patches_per_frame, 128) clean first frame
    video_context: torch.Tensor
    audio_context: torch.Tensor
    ucpe_viewmats: torch.Tensor  # (1, latent_frames, 4, 4) fp32
    ucpe_Ks: torch.Tensor  # noqa: N815  (1, latent_frames, 3, 3) fp32


class EchoWMCausalPipeline(
    nn.Module,
    SupportsComponentDiscovery,
    SupportsStepExecution,
    ProgressBarMixin,
):
    """Causal 4-step DMD rollout for Echo-WM Flash."""

    supports_step_execution: ClassVar[bool] = True
    _dit_modules = ["transformer"]
    _encoder_modules = ["text_stack"]
    _vae_modules: tuple[str, ...] = ()
    dummy_run_num_frames: ClassVar[int] = 0

    def __init__(self, *, od_config: OmniDiffusionConfig, prefix: str = "") -> None:
        super().__init__()
        self.od_config = od_config
        self.model_path = od_config.model
        model_config = dict(getattr(od_config, "model_config", {}) or {})
        self.model_config = model_config
        parallel = getattr(od_config, "parallel_config", None)
        if getattr(parallel, "pipeline_parallel_size", 1) > 1:
            raise ValueError("Echo-WM does not support pipeline parallelism yet")
        if getattr(od_config, "quantization_config", None) is not None:
            raise ValueError("Echo-WM does not support quantization yet")

        checkpoint_config = _read_checkpoint_config(self.model_path)
        self.checkpoint_config = checkpoint_config
        height = int(model_config.get("echo_wm_height", _DEFAULT_RESOLUTION[0]))
        width = int(model_config.get("echo_wm_width", _DEFAULT_RESOLUTION[1]))
        self.ucpe_config = EchoWMUCPEConfig(
            enabled=True,
            attn_dim=1024,
            num_heads=8,
            patches_x=width // 32,
            patches_y=height // 32,
            image_width=width,
            image_height=height,
        )
        self.transformer = EchoWMTransformer3DModel.from_config(
            checkpoint_config.get("transformer", {}),
            ucpe=self.ucpe_config,
            prefix=f"{prefix}transformer." if prefix else "transformer.",
        )
        transformer_cfg = checkpoint_config.get("transformer", {})
        self.text_stack = EchoWMTextStack(
            video_dim=self.transformer.inner_dim,
            audio_dim=self.transformer.audio_inner_dim,
            connector_num_layers=int(transformer_cfg.get("connector_num_layers", 8)),
            video_heads=int(transformer_cfg.get("connector_num_attention_heads", 32)),
            video_head_dim=int(transformer_cfg.get("connector_attention_head_dim", 128)),
            audio_heads=int(transformer_cfg.get("audio_connector_num_attention_heads", 32)),
            audio_head_dim=int(transformer_cfg.get("audio_connector_attention_head_dim", 64)),
            num_registers=int(transformer_cfg.get("connector_num_learnable_registers", 128)),
            rope_max_pos=int(transformer_cfg.get("connector_positional_embedding_max_pos", [4096])[0]),
            apply_gated_attention=bool(transformer_cfg.get("connector_apply_gated_attention", True)),
        )
        # No diffusers component layout: weights load straight from the single
        # Echo-WM safetensors file (see load_weights).
        self.weights_sources = []

        # Optional in-process Gemma encoder (precision runs use fixture
        # embeddings produced by the reference implementation instead).
        self._gemma = None
        self._gemma_tokenizer = None
        self._gemma_path = model_config.get("echo_wm_gemma_path")
        self.device = self._resolve_device()
        self.dtype = torch.bfloat16

    @staticmethod
    def _resolve_device() -> torch.device:
        try:
            from vllm_omni.diffusion.distributed.utils import get_local_device

            return get_local_device()
        except Exception:
            return torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # ------------------------------------------------------------------ weights

    def load_weights(self, weights) -> set[str]:
        """Load transformer and text-stack weights from the single checkpoint."""
        from safetensors import safe_open as _open

        covered: set[str] = set()
        with _open(self.model_path, framework="pt") as handle:
            transformer_keys = []
            text_keys = []
            for name in handle.keys():
                if name.startswith("model.diffusion_model.") and "embeddings_connector" not in name:
                    transformer_keys.append(name)
                elif (
                    name.startswith("model.diffusion_model.")
                    and "embeddings_connector" in name
                    or name.startswith("text_embedding_projection.")
                ):
                    text_keys.append(name)
            transformer_weights = ((name, handle.get_tensor(name)) for name in transformer_keys)
            covered |= self.transformer.load_weights(transformer_weights)
            text_weights = ((name, handle.get_tensor(name)) for name in text_keys)
            covered |= self.text_stack.load_weights(text_weights)
        del weights  # the framework iterator is empty for single-file checkpoints
        return covered

    # ------------------------------------------------------------------ text

    def _encode_prompt(self, prompt: str) -> tuple[torch.Tensor, torch.Tensor]:
        if self._gemma is None:
            if not self._gemma_path:
                raise ValueError(
                    "Echo-WM text encoding requires model_config.echo_wm_gemma_path; "
                    "otherwise pass fixture embeddings via sampling.extra_args.echo_wm_prompt_embeds"
                )
            from transformers import AutoTokenizer, Gemma3ForConditionalGeneration

            self._gemma_tokenizer = AutoTokenizer.from_pretrained(self._gemma_path, local_files_only=True)
            self._gemma_tokenizer.padding_side = "left"
            if self._gemma_tokenizer.pad_token is None:
                self._gemma_tokenizer.pad_token = self._gemma_tokenizer.eos_token
            self._gemma = (
                Gemma3ForConditionalGeneration.from_pretrained(self._gemma_path, torch_dtype=self.dtype)
                .to(self.device)
                .eval()
            )
        encoded = self._gemma_tokenizer(
            prompt.strip(),
            padding="max_length",
            max_length=1024,
            truncation=True,
            return_tensors="pt",
        )
        input_ids = encoded.input_ids.to(self.device)
        attention_mask = encoded.attention_mask.to(self.device)
        with torch.inference_mode():
            hidden_states = self._gemma(
                input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True
            ).hidden_states
        stacked = torch.stack(hidden_states, dim=-1)
        with torch.inference_mode():
            video_context, audio_context = self.text_stack(stacked, attention_mask)
        return video_context, audio_context

    # ------------------------------------------------------------------ request parsing

    def _parse_request(self, req: DiffusionRequestBatch) -> _EchoWMRequestInputs:
        if req.num_reqs != 1 or len(req.prompts) != 1:
            raise ValueError("Echo-WM supports a single prompt request, not request batching.")
        sampling = req.sampling_params
        if int(sampling.num_outputs_per_prompt or 1) != 1:
            raise ValueError("Echo-WM requires num_outputs_per_prompt=1.")
        extra_args = dict(getattr(sampling, "extra_args", None) or {})

        prompt_value = req.prompts[0]
        prompt = (
            prompt_value
            if isinstance(prompt_value, str)
            else (prompt_value.get("prompt") if isinstance(prompt_value, dict) else None)
        )
        height = int(extra_args.get("echo_wm_height", _DEFAULT_RESOLUTION[0]))
        width = int(extra_args.get("echo_wm_width", _DEFAULT_RESOLUTION[1]))
        num_frames = int(sampling.num_frames or extra_args.get("echo_wm_num_frames", 241))
        fps = float(extra_args.get("echo_wm_fps", _DEFAULT_FPS))
        seed = int(getattr(sampling, "seed", None) or extra_args.get("echo_wm_seed", 42))
        steps = int(sampling.num_inference_steps or _ECHOWM_DMD_STEPS)
        if steps != _ECHOWM_DMD_STEPS:
            raise ValueError(f"Echo-WM Flash requires num_inference_steps={_ECHOWM_DMD_STEPS}, got {steps}")

        latent_frames = (num_frames - 1) // 8 + 1
        if num_frames != (latent_frames - 1) * 8 + 1:
            raise ValueError("echo_wm num_frames must be 1 + 8*n")
        cache_config = EchoWMCacheConfig(
            video_local_attn_size=int(extra_args.get("echo_wm_video_local_attn_size", 19)),
            video_sink_size=int(extra_args.get("echo_wm_video_sink_size", 7)),
        )
        cache_config.validate()
        causal_video_blocks(latent_frames, cache_config.video_chunk_size)

        image_tokens = extra_args.get("echo_wm_image_latent")
        if not isinstance(image_tokens, torch.Tensor) or image_tokens.ndim != 3:
            raise ValueError(
                "Echo-WM v1 requires sampling.extra_args.echo_wm_image_latent: the pre-encoded "
                "first-frame latent tokens of shape (1, patches_per_frame, 128) (VAE encode is not "
                "yet in-engine)"
            )
        patches_per_frame = (height // 32) * (width // 32)
        channels = self.transformer.config.in_channels
        if image_tokens.shape != (1, patches_per_frame, channels):
            raise ValueError(
                f"echo_wm_image_latent must have shape (1, {patches_per_frame}, {channels}), "
                f"got {tuple(image_tokens.shape)}"
            )

        embeddings = extra_args.get("echo_wm_prompt_embeds")
        if embeddings is not None:
            video_context, audio_context = embeddings
        elif isinstance(prompt, str) and prompt.strip():
            video_context, audio_context = self._encode_prompt(prompt)
        else:
            raise ValueError(
                "Echo-WM requires either sampling.extra_args.echo_wm_prompt_embeds "
                "(video/audio context tensors) or a text prompt with echo_wm_gemma_path configured"
            )

        action = extra_args.get("echo_wm_action")
        if not isinstance(action, dict) or "ucpe_viewmats" not in action or "ucpe_Ks" not in action:
            raise ValueError(
                "Echo-WM requires sampling.extra_args.echo_wm_action: a dict with fp32 "
                "ucpe_viewmats (1, latent_frames, 4, 4) and ucpe_Ks (1, latent_frames, 3, 3)"
            )
        viewmats = action["ucpe_viewmats"]
        ks = action["ucpe_Ks"]
        if tuple(viewmats.shape) != (1, latent_frames, 4, 4) or tuple(ks.shape) != (1, latent_frames, 3, 3):
            raise ValueError(
                f"echo_wm_action arrays must cover {latent_frames} latent frames, got "
                f"{tuple(viewmats.shape)} / {tuple(ks.shape)}"
            )
        device = self.transformer.patchify_proj.weight.device
        timesteps = tuple(extra_args.get("echo_wm_timesteps", DEFAULT_CAUSAL_TIMESTEPS))
        return _EchoWMRequestInputs(
            height=height,
            width=width,
            num_frames=num_frames,
            fps=fps,
            seed=seed,
            timesteps=timesteps,
            cache_config=cache_config,
            image_latent_tokens=image_tokens.to(device=device, dtype=self.dtype),
            video_context=video_context.to(device=device, dtype=self.dtype),
            audio_context=audio_context.to(device=device, dtype=self.dtype),
            ucpe_viewmats=viewmats.to(device=device, dtype=torch.float32),
            ucpe_Ks=ks.to(device=device, dtype=torch.float32),
        )

    # ------------------------------------------------------------------ session state

    def _init_session(self, inputs: _EchoWMRequestInputs):
        """Allocate caches, RoPE templates, and the initial noise buffers."""
        device = self.transformer.patchify_proj.weight.device
        patches_per_frame = (inputs.height // 32) * (inputs.width // 32)
        latent_frames = (inputs.num_frames - 1) // 8 + 1
        audio_frames = causal_audio_frames(latent_frames, inputs.cache_config.video_chunk_size)
        caches = self.transformer.allocate_caches(
            batch_size=1,
            patches_per_frame=patches_per_frame,
            text_seq_len=inputs.video_context.shape[1],
            cache_config=inputs.cache_config,
            device=device,
            dtype=self.dtype,
        )
        video_positions = build_video_positions(
            latent_frames, inputs.height, inputs.width, fps=inputs.fps, device=device
        )
        audio_positions = build_audio_positions(audio_frames, device=device)
        video_window = inputs.cache_config.video_local_attn_size * patches_per_frame
        video_rope = make_split_rope(
            video_positions[:, :, :video_window],
            dim=self.transformer.inner_dim,
            num_heads=self.transformer.config.num_attention_heads,
            max_pos=list(self.transformer.config.positional_embedding_max_pos),
            out_dtype=self.dtype,
            device=device,
        )
        audio_rope = make_split_rope(
            audio_positions[:, :, : inputs.cache_config.audio_local_attn_size],
            dim=self.transformer.audio_inner_dim,
            num_heads=self.transformer.config.audio_num_attention_heads,
            max_pos=list(self.transformer.config.audio_positional_embedding_max_pos),
            out_dtype=self.dtype,
            device=device,
        )
        cross_max_pos = max(
            self.transformer.config.positional_embedding_max_pos[0],
            self.transformer.config.audio_positional_embedding_max_pos[0],
        )
        video_cross_rope = make_cross_rope_template(
            video_positions[:, :, :video_window],
            dim=self.transformer.config.audio_cross_attention_dim,
            num_heads=self.transformer.config.audio_num_attention_heads,
            max_pos=cross_max_pos,
            out_dtype=self.dtype,
            device=device,
        )
        audio_cross_rope = make_cross_rope_template(
            audio_positions[:, :, : inputs.cache_config.audio_local_attn_size],
            dim=self.transformer.config.audio_cross_attention_dim,
            num_heads=self.transformer.config.audio_num_attention_heads,
            max_pos=cross_max_pos,
            out_dtype=self.dtype,
            device=device,
        )
        a2v_slices, v2a_slices = compute_cross_slices(latent_frames, patches_per_frame, inputs.cache_config)
        for layer in caches:
            layer.video_rope = video_rope
            layer.audio_rope = audio_rope
            layer.video_cross_rope = video_cross_rope
            layer.audio_cross_rope = audio_cross_rope
            layer.a2v_q_slices = a2v_slices
            layer.v2a_q_slices = v2a_slices
            layer.ucpe_full_viewmats = inputs.ucpe_viewmats
            layer.ucpe_full_Ks = inputs.ucpe_Ks

        sigmas = resolve_causal_sigmas(list(inputs.timesteps))
        video_blocks = causal_video_blocks(latent_frames, inputs.cache_config.video_chunk_size)
        audio_blocks = causal_audio_blocks(latent_frames, inputs.cache_config.video_chunk_size)

        # Noise draw order is pinned by the reference rollout: initial video,
        # then audio, then the per-step re-noising draws in block order.
        generator = torch.Generator(device=device).manual_seed(inputs.seed)
        total_video_tokens = latent_frames * patches_per_frame
        channels = self.transformer.config.in_channels
        initial_video = torch.randn(
            (1, total_video_tokens, channels), generator=generator, device=device, dtype=self.dtype
        )
        initial_audio = torch.randn((1, audio_frames, channels), generator=generator, device=device, dtype=self.dtype)
        return SimpleNamespace(
            caches=caches,
            sigmas=sigmas,
            video_blocks=video_blocks,
            audio_blocks=audio_blocks,
            patches_per_frame=patches_per_frame,
            initial_video=initial_video,
            initial_audio=initial_audio,
            generator=generator,
            video_output=None,
            audio_output=None,
        )

    # ------------------------------------------------------------------ rollout math

    def _forward_block(
        self,
        session,
        inputs: _EchoWMRequestInputs,
        video_tokens: torch.Tensor | None,
        audio_tokens: torch.Tensor | None,
        video_sigma: float,
        audio_sigma: float | None,
        video_start: int,
        audio_start: int,
    ) -> tuple[torch.Tensor | None, torch.Tensor | None]:
        """One transformer forward; velocities converted to x0 in fp32."""
        ppf = session.patches_per_frame
        if video_tokens is not None:
            video_frames_end = (video_start + video_tokens.shape[1]) // ppf
        else:
            video_frames_end = video_start // ppf
        viewmats = inputs.ucpe_viewmats[:, video_start // ppf : video_frames_end] if video_tokens is not None else None
        ks = inputs.ucpe_Ks[:, video_start // ppf : video_frames_end] if video_tokens is not None else None
        with torch.inference_mode():
            velocity_video, velocity_audio = self.transformer(
                video_tokens=video_tokens,
                audio_tokens=audio_tokens,
                video_sigma=video_sigma,
                audio_sigma=audio_sigma,
                video_context=inputs.video_context,
                audio_context=inputs.audio_context,
                caches=session.caches,
                video_token_start=video_start,
                audio_token_start=audio_start,
                ucpe_viewmats=viewmats,
                ucpe_Ks=ks,
                patches_per_frame=ppf,
            )
        video_x0 = audio_x0 = None
        if velocity_video is not None and video_tokens is not None:
            video_x0 = (video_tokens.float() - velocity_video.float() * video_sigma).to(video_tokens.dtype)
        if velocity_audio is not None and audio_tokens is not None:
            sigma = audio_sigma if audio_sigma is not None else video_sigma
            audio_x0 = (audio_tokens.float() - velocity_audio.float() * sigma).to(audio_tokens.dtype)
        return video_x0, audio_x0

    @staticmethod
    def _advance(denoised: torch.Tensor, next_sigma: float, generator: torch.Generator) -> torch.Tensor:
        noise = torch.randn(denoised.shape, generator=generator, device=denoised.device, dtype=denoised.dtype)
        return (1 - next_sigma) * denoised + next_sigma * noise

    def _prepare_outputs(self, session, inputs: _EchoWMRequestInputs) -> None:
        latent_frames = (inputs.num_frames - 1) // 8 + 1
        audio_frames = causal_audio_frames(latent_frames, inputs.cache_config.video_chunk_size)
        channels = session.initial_video.shape[-1]
        session.video_output = torch.zeros(
            (1, latent_frames * session.patches_per_frame, channels),
            device=session.initial_video.device,
            dtype=self.dtype,
        )
        session.audio_output = torch.zeros(
            (1, audio_frames, channels), device=session.initial_audio.device, dtype=self.dtype
        )
        session.video_output[:, : session.patches_per_frame] = inputs.image_latent_tokens

    # ------------------------------------------------------------------ request mode

    def forward(self, req: DiffusionRequestBatch) -> DiffusionOutput:
        inputs = self._parse_request(req)
        session = self._init_session(inputs)
        self._prepare_outputs(session, inputs)
        ppf = session.patches_per_frame
        sigmas = session.sigmas

        with torch.inference_mode():
            # Image-sink commit: the clean first frame enters the video caches.
            self._forward_block(session, inputs, inputs.image_latent_tokens, None, 0.0, None, 0, 0)
            # Audio prefix: 4 steps with the clean image at sigma 0.
            audio_start, audio_end = session.audio_blocks[0]
            audio_sample = session.initial_audio[:, audio_start:audio_end]
            for step, sigma in enumerate(sigmas):
                _, denoised_audio = self._forward_block(
                    session, inputs, inputs.image_latent_tokens, audio_sample, 0.0, sigma, 0, audio_start
                )
                audio_sample = (
                    denoised_audio
                    if step == len(sigmas) - 1
                    else self._advance(denoised_audio, sigmas[step + 1], session.generator)
                )
            session.audio_output[:, audio_start:audio_end] = audio_sample
            # Clean commit for the prefix.
            self._forward_block(session, inputs, inputs.image_latent_tokens, audio_sample, 0.0, 0.0, 0, audio_start)

            # Audio-video blocks.
            for video_block, audio_block in zip(session.video_blocks[1:], session.audio_blocks[1:], strict=True):
                video_start, video_end = video_block
                audio_start, audio_end = audio_block
                video_sample = session.initial_video[:, video_start * ppf : video_end * ppf]
                audio_sample = session.initial_audio[:, audio_start:audio_end]
                for step, sigma in enumerate(sigmas):
                    denoised_video, denoised_audio = self._forward_block(
                        session,
                        inputs,
                        video_sample,
                        audio_sample,
                        sigma,
                        sigma,
                        video_start * ppf,
                        audio_start,
                    )
                    if step == len(sigmas) - 1:
                        video_sample, audio_sample = denoised_video, denoised_audio
                    else:
                        video_sample = self._advance(denoised_video, sigmas[step + 1], session.generator)
                        audio_sample = self._advance(denoised_audio, sigmas[step + 1], session.generator)
                session.video_output[:, video_start * ppf : video_end * ppf] = video_sample
                session.audio_output[:, audio_start:audio_end] = audio_sample
                # Clean refresh commit.
                self._forward_block(
                    session, inputs, video_sample, audio_sample, 0.0, 0.0, video_start * ppf, audio_start
                )

        return DiffusionOutput(
            output={
                "payload": {
                    "latents": {
                        "video": session.video_output,
                        "audio": session.audio_output,
                        "patches_per_frame": ppf,
                        "latent_frames": session.video_output.shape[1] // ppf,
                        "audio_frames": session.audio_output.shape[1],
                    },
                },
                "metadata": {"echo_wm": {"seed": inputs.seed, "timesteps": list(inputs.timesteps)}},
            },
        )

    # ------------------------------------------------------------------ stepwise execution

    def prepare_encode(self, state: StepRequestState, **kwargs) -> StepRequestState:
        """Validate the request, initialize the session, and prime the image sink."""
        req = kwargs.get("request_batch")
        if req is None:
            raise ValueError("Echo-WM stepwise execution requires the request batch")
        inputs = self._parse_request(req)
        session = self._init_session(inputs)
        self._prepare_outputs(session, inputs)
        # The image-sink commit writes the clean first frame into the caches;
        # it is not a denoising step and produces no chunk.
        self._forward_block(session, inputs, inputs.image_latent_tokens, None, 0.0, None, 0, 0)
        state.extra = {
            "echo_wm_inputs": inputs,
            "echo_wm_session": session,
        }
        state.total_chunks = len(session.video_blocks)  # prefix block + AV blocks
        state.chunk_num_steps = _ECHOWM_DMD_STEPS
        state.chunk_index = 0
        state.step_in_chunk = 0
        self._prepare_next_chunk(state)
        return state

    def _prepare_next_chunk(self, state: StepRequestState) -> None:
        session: SimpleNamespace = state.extra["echo_wm_session"]
        inputs: _EchoWMRequestInputs = state.extra["echo_wm_inputs"]
        ppf = session.patches_per_frame
        video_block = session.video_blocks[state.chunk_index]
        audio_block = session.audio_blocks[state.chunk_index]
        video_start, video_end = video_block
        audio_start, audio_end = audio_block
        if state.chunk_index == 0:
            session.current_video_sample = inputs.image_latent_tokens
            session.current_audio_sample = session.initial_audio[:, audio_start:audio_end]
        else:
            session.current_video_sample = session.initial_video[:, video_start * ppf : video_end * ppf]
            session.current_audio_sample = session.initial_audio[:, audio_start:audio_end]
        session.current_video_start = video_start * ppf
        session.current_audio_start = audio_start

    def denoise_step(self, input_batch, *, states=None, **kwargs):
        state = states[0]
        session: SimpleNamespace = state.extra["echo_wm_session"]
        inputs: _EchoWMRequestInputs = state.extra["echo_wm_inputs"]
        sigma = session.sigmas[state.step_in_chunk]
        if state.chunk_index == 0:
            video_sigma = 0.0
            audio_sigma = sigma
        else:
            video_sigma = audio_sigma = sigma
        video_x0, audio_x0 = self._forward_block(
            session,
            inputs,
            session.current_video_sample,
            session.current_audio_sample,
            video_sigma,
            audio_sigma,
            session.current_video_start,
            session.current_audio_start,
        )
        state.extra["echo_wm_step_result"] = (video_x0, audio_x0, sigma)
        return None

    def step_scheduler(self, state: StepRequestState, noise_pred, **kwargs) -> None:
        session: SimpleNamespace = state.extra["echo_wm_session"]
        video_x0, audio_x0, sigma = state.extra.pop("echo_wm_step_result")
        step = state.step_in_chunk
        sigmas = session.sigmas
        if step == len(sigmas) - 1:
            session.current_video_sample = video_x0
            session.current_audio_sample = audio_x0
        else:
            next_sigma = sigmas[step + 1]
            if state.chunk_index == 0:
                session.current_audio_sample = self._advance(audio_x0, next_sigma, session.generator)
            else:
                session.current_video_sample = self._advance(video_x0, next_sigma, session.generator)
                session.current_audio_sample = self._advance(audio_x0, next_sigma, session.generator)
        state.step_in_chunk += 1

    def post_decode(self, state: StepRequestState, **kwargs) -> DiffusionOutput:
        session: SimpleNamespace = state.extra["echo_wm_session"]
        inputs: _EchoWMRequestInputs = state.extra["echo_wm_inputs"]
        ppf = session.patches_per_frame
        video_block = session.video_blocks[state.chunk_index]
        audio_block = session.audio_blocks[state.chunk_index]
        video_start, video_end = video_block
        audio_start, audio_end = audio_block
        if state.chunk_index == 0:
            session.video_output[:, :ppf] = inputs.image_latent_tokens
        else:
            session.video_output[:, video_start * ppf : video_end * ppf] = session.current_video_sample
        session.audio_output[:, audio_start:audio_end] = session.current_audio_sample
        # Clean refresh forward replaces the block in the caches.
        self._forward_block(
            session,
            inputs,
            session.current_video_sample,
            session.current_audio_sample,
            0.0,
            0.0,
            video_start * ppf,
            audio_start,
        )
        finished = state.chunk_index + 1 >= state.total_chunks
        chunk_payload = {
            "video": session.video_output[:, video_start * ppf : video_end * ppf],
            "audio": session.audio_output[:, audio_start:audio_end],
        }
        state.chunk_index += 1
        state.step_in_chunk = 0
        if not finished:
            self._prepare_next_chunk(state)
        return DiffusionOutput(
            output={
                "payload": {"latents": chunk_payload},
                "metadata": {
                    "echo_wm": {
                        "chunk_index": state.chunk_index - 1,
                        "total_chunks": state.total_chunks,
                        "seed": inputs.seed,
                    }
                },
            },
            chunk_index=state.chunk_index - 1,
            total_chunks=state.total_chunks,
            finished=finished,
        )
